# AutoDetect=off: wyłącz wykrywanie sprzętu przez nvidia-smi
# Konieczne gdy nie ma fizycznych GPU
AutoDetect=off

# Slurm 21.08 wymaga File= żeby prawidłowo zarejestrować GPU w slurmctld.
# Pliki /dev/nvidiaX tworzymy jako puste placeholdery w entrypoint.sh
Name=gpu Type=tesla File=/dev/nvidia[0-3]
